Miniconda: To make conda operate correctly, please run: 
            source $UCL_CONDA_PATH/etc/profile.d/conda.sh 

Loading python/miniconda3/24.3.0-0
  Loading requirement: gcc-libs/10.2.0
Generating train split:   0%|          | 0/87925 [00:00<?, ? examples/s]Generating train split: 100%|██████████| 87925/87925 [00:00<00:00, 1976028.27 examples/s]
Generating validation split:   0%|          | 0/3610 [00:00<?, ? examples/s]Generating validation split: 100%|██████████| 3610/3610 [00:00<00:00, 762370.35 examples/s]
`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'qa_srl' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.
Traceback (most recent call last):
  File "/home/zceccgr/Scratch/freezeLLM/llm_scale_up/pretrain_wikitext_finetune_qasrl.py", line 709, in <module>
    qa_train_dataset = QASRLDataset(
                       ^^^^^^^^^^^^^
  File "/home/zceccgr/Scratch/freezeLLM/llm_scale_up/pretrain_wikitext_finetune_qasrl.py", line 355, in __init__
    self.dataset = load_dataset("qa_srl", split=split, trust_remote_code=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zceccgr/.conda/envs/llm-env/lib/python3.12/site-packages/datasets/load.py", line 1392, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zceccgr/.conda/envs/llm-env/lib/python3.12/site-packages/datasets/load.py", line 1132, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zceccgr/.conda/envs/llm-env/lib/python3.12/site-packages/datasets/load.py", line 1031, in dataset_module_factory
    raise e1 from None
  File "/home/zceccgr/.conda/envs/llm-env/lib/python3.12/site-packages/datasets/load.py", line 989, in dataset_module_factory
    raise RuntimeError(f"Dataset scripts are no longer supported, but found {filename}")
RuntimeError: Dataset scripts are no longer supported, but found qa_srl.py
